# EXERCISE (SET 2)

# DATA ANALYSIS WITH PANDAS

In [1]:
#importing required labraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# SERIES

1.	Write a Pandas program to compare the elements of two Pandas series. 
    Sample Series [4,65,436,3,9], [7,0,3,897,9]

In [2]:
SER_1 = pd.Series([4, 65, 436, 3, 9])
SER_2 = pd.Series([7, 0, 3, 897, 9])

result = SER_1 == SER_2
print(result)

0    False
1    False
2    False
3    False
4     True
dtype: bool

2.	Write a Pandas program to add, subtract, multiply and divide two Pandas series. 
Sample Series: [2,4,6,8,14], [1,3,5,7,9]

In [3]:
SER1 = pd.Series([2, 4, 6, 8, 14])
SER2 = pd.Series([1, 3, 5, 7, 9])

addition = SER1 + SER2
subtraction = SER1 - SER2
multiplication = SER1 * SER2
division = SER1 / SER2

print("Addition:")
print(addition)
print("\nSubtraction:")
print(subtraction)
print("\nMultiplication:")
print(multiplication)
print("\nDivision:")
print(division)

Addition:
0     3
1     7
2    11
3    15
4    23
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    5
dtype: int64

Multiplication:
0      2
1     12
2     30
3     56
4    126
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.555556
dtype: float64

3.	Write a Pandas program to convert a dictionary to a Pandas series. 
Sample dictionary: dictionary1 = {‘Josh’: 24, ‘Sam’: 36, ‘Peace’: 19, ‘Charles’: 65, ‘Tom’: 44}

In [4]:
DIC_1 = {'Josh': 24, 'Sam': 36, 'Peace': 19, 'Charles': 65, 'Tom': 44}

SERIES = pd.Series(DIC_1)
print(SERIES)

Josh       24
Sam        36
Peace      19
Charles    65
Tom        44
dtype: int64

4.	Write a Pandas program to convert a given series to an array.
Sample series: [‘Love’, 800, ‘Joy’, 789.9, ‘Peace’, True]

In [5]:
series_1 = pd.Series(['Love', 800, 'Joy', 789.9, 'Peace', True])

array_1 = np.array(series_1)
print(array_1)

['Love' 800 'Joy' 789.9 'Peace' True]

5.	Write a Pandas program to display the most frequent value in the given series and replace everything else as ‘Other’ in the series. (Use the ‘HomeTeamGoals’ column in the dataset provided)

In [6]:
# loading dataset here to check for HomeTeamGoals column
DF = pd.read_csv('AfricaCupofNationsMatches.csv')

series = pd.Series(DF.HomeTeamGoals)

most_frequent_value = series.mode()[0]
series = series.map(lambda x: most_frequent_value if x == most_frequent_value else 'Other')

print(series)

0        1.0
1      Other
2      Other
3      Other
4        1.0
       ...
617    Other
618      1.0
619    Other
620    Other
621    Other
Name: HomeTeamGoals, Length: 622, dtype: object

# DATAFRAMES

In [7]:
# importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt # not used in the below dataset

1.	Write a Pandas program to read the given csv file.

In [8]:
# loading the csv file
DF = pd.read_csv('AfricaCupofNationsMatches.csv')
DF

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

2.	Write a Pandas program to get the first 7 rows of your data frame.

In [9]:
# checking for the first 7 rows using head() method
first_7_rows = DF.head(7)
print(first_7_rows)

   Year      Date  Time    HomeTeam       AwayTeam  HomeTeamGoals  \
0  1957  10-Feb-57   NaN     Sudan           Egypt            1.0
1  1957  10-Feb-57   NaN  Ethiopia    South Africa            NaN
2  1957  16-Feb-57   NaN     Egypt        Ethiopia            4.0
3  1959  22-May-59   NaN      Egypt       Ethiopia            4.0
4  1959  25-May-59   NaN     Sudan        Ethiopia            1.0
5  1959  29-May-59   NaN      Egypt          Sudan            2.0
6  1962  14-Jan-62   NaN  Ethiopia         Tunisia            4.0

   AwayTeamGoals             Stage  \
0            2.0        Semifinals
1            NaN        Semifinals
2            0.0             Final
3            0.0  Final Tournament
4            0.0  Final Tournament
5            1.0  Final Tournament
6            2.0        Semifinals

                                SpecialWinConditions                 Stadium  \
0                                                NaN       Municipal Stadium
1  Ethiopia  wins due to disqualification of othe...                     NaN
2                                                NaN       Municipal Stadium
3                                                NaN   Prince Farouk Stadium
4                                                NaN   Prince Farouk Stadium
5                                                NaN   Prince Farouk Stadium
6                                                NaN  Hailé Sélassié Stadium

           City  Attendance
0      Khartoum     30000.0
1           NaN         NaN
2      Khartoum     30000.0
3         Cairo     30000.0
4         Cairo     20000.0
5         Cairo     30000.0
6   Addis Ababa     30000.0

3.	Write a Pandas program to select the ‘HomeTeam’, ‘AwayTeam’, ‘HomeTeamGoals’ and ‘AwayTeamGoals’ columns from your data frame.

In [10]:
# selecting the below columns 
selected_columns = DF[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]
print(selected_columns)

        HomeTeam       AwayTeam  HomeTeamGoals  AwayTeamGoals
0         Sudan           Egypt            1.0            2.0
1      Ethiopia    South Africa            NaN            NaN
2         Egypt        Ethiopia            4.0            0.0
3          Egypt       Ethiopia            4.0            0.0
4         Sudan        Ethiopia            1.0            0.0
..           ...            ...            ...            ...
617  Madagascar         Tunisia            0.0            3.0
618     Senegal         Tunisia            1.0            0.0
619     Algeria         Nigeria            2.0            1.0
620     Tunisia         Nigeria            0.0            1.0
621     Senegal         Algeria            0.0            1.0

[622 rows x 4 columns]

4.	Write a Pandas program to select the rows where Egypt appears.

In [11]:
# checking for the rows containing EGYPT
egypt_row = DF[DF['HomeTeam'] == 'Egypt']
print(egypt_row)

    Year      Date  Time  HomeTeam   AwayTeam  HomeTeamGoals  AwayTeamGoals  \
3   1959  22-May-59   NaN    Egypt   Ethiopia            4.0            0.0
5   1959  29-May-59   NaN    Egypt      Sudan            2.0            1.0
7   1962  18-Jan-62   NaN    Egypt     Uganda            2.0            1.0
13  1963  24-Nov-63   NaN    Egypt    Nigeria            6.0            3.0
14  1963  26-Nov-63   NaN    Egypt      Sudan            2.0            2.0
16  1963  30-Nov-63   NaN    Egypt   Ethiopia            3.0            0.0

                Stage SpecialWinConditions                 Stadium  \
3    Final Tournament                  NaN   Prince Farouk Stadium
5    Final Tournament                  NaN   Prince Farouk Stadium
7          Semifinals                  NaN  Hailé Sélassié Stadium
13            Group B                  NaN   Kumasi Sports Stadium
14            Group B                  NaN   Kumasi Sports Stadium
16  Third place match                  NaN    Accra Sports Stadium

            City  Attendance
3          Cairo     30000.0
5          Cairo     30000.0
7    Addis Ababa     30000.0
13        Kumasi         NaN
14        Kumasi         NaN
16         Accra         NaN

5.	Write a Pandas program to count the number of rows and columns of your data frame.

In [12]:
# checking rows and columns using shape() method
num_rows, num_columns = DF.shape
print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

Number of rows: 622
Number of columns: 12

6.	Write a Pandas program to select the rows where the ‘Attendance’ is missing.

In [13]:
# checking for null values in the Attendance column
missing_attendance_rows = DF[DF['Attendance'].isnull()]
print(missing_attendance_rows)

     Year                         Date   Time        HomeTeam       AwayTeam  \
1    1957                     10-Feb-57    NaN      Ethiopia    South Africa
8    1962                     20-Jan-62    NaN       Tunisia          Uganda
9    1962                     21-Jan-62    NaN      Ethiopia           Egypt
10   1963                     24-Nov-63    NaN         Ghana         Tunisia
11   1963                     26-Nov-63    NaN         Ghana        Ethiopia
..    ...                           ...    ...            ...            ...
565  2017  29 January 2017 (2017-01-29)  20:00         Egypt         Morocco
566  2017  1 February 2017 (2017-02-01)  20:00  Burkina Faso           Egypt
567  2017  2 February 2017 (2017-02-02)  20:00      Cameroon           Ghana
568  2017  4 February 2017 (2017-02-04)  20:00  Burkina Faso           Ghana
569  2017  5 February 2017 (2017-02-05)  20:00         Egypt        Cameroon

     HomeTeamGoals  AwayTeamGoals                 Stage  \
1              NaN            NaN            Semifinals
8              3.0            0.0     Third place match
9              4.0            2.0                 Final
10             1.0            1.0               Group A
11             2.0            0.0               Group A
..             ...            ...                   ...
565            1.0            0.0        Quarter-finals
566            1.0            1.0           Semi-finals
567            2.0            0.0           Semi-finals
568            1.0            0.0  Third place play-off
569            1.0            2.0                 Final

                                  SpecialWinConditions  \
1    Ethiopia  wins due to disqualification of othe...
8                                                  NaN
9                                win after extra time
10                                                 NaN
11                                                 NaN
..                                                 ...
565                                                NaN
566                        Egypt win on Penalities 3-4
567                                                NaN
568                                                NaN
569                                                NaN

                    Stadium          City  Attendance
1                       NaN           NaN         NaN
8    Hailé Sélassié Stadium   Addis Ababa         NaN
9    Hailé Sélassié Stadium   Addis Ababa         NaN
10     Accra Sports Stadium         Accra         NaN
11     Accra Sports Stadium         Accra         NaN
..                      ...           ...         ...
565    Stade de Port-Gentil   Port-Gentil         NaN
566       Stade de l'Amitié    Libreville         NaN
567    Stade de Franceville   Franceville         NaN
568    Stade de Port-Gentil   Port-Gentil         NaN
569       Stade de l'Amitié    Libreville         NaN

[100 rows x 12 columns]

7.	Write a Pandas program to select the rows where the ‘HomeTeamGoals’ are between 3 and 6 inclusive.

In [14]:
# checking for the range in HomeTeamGoals from 3 to 6 inclusively
selected_rows = DF[(DF['HomeTeamGoals'] >= 3) & (DF['HomeTeamGoals'] <= 6)]
print(selected_rows)

     Year                         Date   Time    HomeTeam     AwayTeam  \
2    1957                     16-Feb-57    NaN     Egypt      Ethiopia
3    1959                     22-May-59    NaN      Egypt     Ethiopia
6    1962                     14-Jan-62    NaN  Ethiopia       Tunisia
8    1962                     20-Jan-62    NaN   Tunisia        Uganda
9    1962                     21-Jan-62    NaN  Ethiopia         Egypt
..    ...                           ...    ...        ...          ...
553  2017  20 January 2017 (2017-01-20)  20:00   Morocco          Togo
585  2019     27 June 2019 (2019-06-27)  22:00     Kenya      Tanzania
595  2019     24 June 2019 (2019-06-24)  22:00      Mali    Mauritania
608  2019      6 July 2019 (2019-07-06)  18:00   Nigeria      Cameroon
611  2019      7 July 2019 (2019-07-07)  21:00   Algeria        Guinea

     HomeTeamGoals  AwayTeamGoals              Stage    SpecialWinConditions  \
2              4.0            0.0              Final                     NaN
3              4.0            0.0   Final Tournament                     NaN
6              4.0            2.0         Semifinals                     NaN
8              3.0            0.0  Third place match                     NaN
9              4.0            2.0              Final   win after extra time
..             ...            ...                ...                     ...
553            3.0            1.0            Group C                     NaN
585            3.0            2.0            Group C                     NaN
595            4.0            1.0            Group E                     NaN
608            3.0            2.0        Round of 16                     NaN
611            3.0            0.0        Round of 16                     NaN

                    Stadium          City  Attendance
2         Municipal Stadium      Khartoum     30000.0
3     Prince Farouk Stadium         Cairo     30000.0
6    Hailé Sélassié Stadium   Addis Ababa     30000.0
8    Hailé Sélassié Stadium   Addis Ababa         NaN
9    Hailé Sélassié Stadium   Addis Ababa         NaN
..                      ...           ...         ...
553            Stade d'Oyem          Oyem         NaN
585         30 June Stadium         Cairo      7233.0
595            Suez Stadium          Suez      6202.0
608      Alexandria Stadium    Alexandria     10000.0
611         30 June Stadium         Cairo      8205.0

[138 rows x 12 columns]

8.	Write a Pandas program to change the “AwayTeamGoals” in the 3rd row to 10.

In [15]:
# At index 2 AwayTeamGoals is changed to 10
DF.loc[2, 'AwayTeamGoals'] = 10
print(DF)

     Year                      Date   Time      HomeTeam       AwayTeam  \
0    1957                  10-Feb-57    NaN       Sudan           Egypt
1    1957                  10-Feb-57    NaN    Ethiopia    South Africa
2    1957                  16-Feb-57    NaN       Egypt        Ethiopia
3    1959                  22-May-59    NaN        Egypt       Ethiopia
4    1959                  25-May-59    NaN       Sudan        Ethiopia
..    ...                        ...    ...          ...            ...
617  2019  11 July 2019 (2019-07-11)  21:00  Madagascar         Tunisia
618  2019  14 July 2019 (2019-07-14)  18:00     Senegal         Tunisia
619  2019  14 July 2019 (2019-07-14)  21:00     Algeria         Nigeria
620  2019  17 July 2019 (2019-07-17)  21:00     Tunisia         Nigeria
621  2019  19 July 2019 (2019-07-19)  21:00     Senegal         Algeria

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
617            0.0            3.0        Quarter-finals
618            1.0            0.0           Semi-finals
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
617                                                NaN
618                              win after extra time
619                                                NaN
620                                                NaN
621                                                NaN

                         Stadium       City  Attendance
0              Municipal Stadium   Khartoum     30000.0
1                            NaN        NaN         NaN
2              Municipal Stadium   Khartoum     30000.0
3          Prince Farouk Stadium      Cairo     30000.0
4          Prince Farouk Stadium      Cairo     20000.0
..                           ...        ...         ...
617             Al Salam Stadium      Cairo      7568.0
618              30 June Stadium      Cairo      9143.0
619  Cairo International Stadium      Cairo     49775.0
620             Al Salam Stadium      Cairo      6340.0
621  Cairo International Stadium      Cairo     75000.0

[622 rows x 12 columns]

9.	Write a Pandas program to sort the DataFrame first by ‘HomeTeam’ in ascending order, then by ‘HomeTeamScores’ in descending order.

In [16]:
# HomeTeam is sorted in ascending order
sorted_data_frame =DF.sort_values(by='HomeTeam', ascending=True)
print(sorted_data_frame)

     Year                         Date   Time    HomeTeam   AwayTeam  \
403  2004                      3-Feb-04  14:00   Algeria    Zimbabwe
229  1992                     17-Jan-92    NaN   Algeria       Congo
291  1998                      8-Feb-98  20:30   Algeria      Guinea
544  2017  15 January 2017 (2017-01-15)  17:00   Algeria    Zimbabwe
148  1982                      7-Mar-82    NaN   Algeria      Zambia
..    ...                           ...    ...        ...        ...
230  1992                     13-Jan-92    NaN    Zambia       Egypt
575  2019     30 June 2019 (2019-06-30)  21:00  Zimbabwe    DR Congo
437  2006                     23-Jan-06  20:00  Zimbabwe     Senegal
549  2017  23 January 2017 (2017-01-23)  20:00  Zimbabwe     Tunisia
398  2004                     25-Jan-04  16:30  Zimbabwe       Egypt

     HomeTeamGoals  AwayTeamGoals    Stage SpecialWinConditions  \
403            1.0            2.0  Group C                  NaN
229            1.0            1.0  Group C                  NaN
291            0.0            1.0  Group A                  NaN
544            2.0            2.0  Group B                  NaN
148            1.0            0.0  Group B                  NaN
..             ...            ...      ...                  ...
230            1.0            0.0  Group D                  NaN
575            0.0            4.0  Group A                  NaN
437            0.0            2.0  Group D                  NaN
549            2.0            4.0  Group B                  NaN
398            1.0            2.0  Group C                  NaN

                       Stadium          City  Attendance
403  Stade Olympique de Sousse        Sousse     10000.0
229   Stade Aline Sitoe Diatta    Ziguinchor      5000.0
291            Stade Municipal   Ouagadougou      3000.0
544       Stade de Franceville   Franceville         NaN
148           28 March Stadium      Benghazi      5000.0
..                         ...           ...         ...
230   Stade Aline Sitoe Diatta    Ziguinchor      5000.0
575            30 June Stadium         Cairo      4364.0
437          Port Said Stadium     Port Said     15000.0
549          Stade de l'Amitié    Libreville         NaN
398       Stade Taïeb El Mhiri          Sfax     22000.0

[622 rows x 12 columns]

In [17]:
# HomeTeamGoals is sorted in descending order
sorted_data_frame =DF.sort_values(by='HomeTeamGoals', ascending=False)
print(sorted_data_frame)

     Year                      Date   Time        HomeTeam  \
13   1963                  24-Nov-63    NaN          Egypt
46   1970                  10-Feb-70    NaN   Ivory Coast
72   1972                   4-Mar-72    NaN      Cameroon
21   1965                  12-Nov-65    NaN         Ghana
400  2004                  29-Jan-04  16:30      Cameroon
..    ...                        ...    ...            ...
621  2019  19 July 2019 (2019-07-19)  21:00       Senegal
1    1957                  10-Feb-57    NaN      Ethiopia
489  2010                  11-Jan-10  19:30         Ghana
490  2010                  15-Jan-10  17:00  Burkina Faso
493  2010                  19-Jan-10  17:00   Ivory Coast

                 AwayTeam  HomeTeamGoals  AwayTeamGoals              Stage  \
13                Nigeria            6.0            3.0            Group B
46               Ethiopia            6.0            1.0            Group A
72                  Zaire            5.0            2.0  Third place match
21    Congo-Léopoldville            5.0            2.0            Group B
400              Zimbabwe            5.0            3.0            Group C
..                    ...            ...            ...                ...
621               Algeria            0.0            1.0              Final
1            South Africa            NaN            NaN         Semifinals
489                  Togo            NaN            NaN            Group B
490                  Togo            NaN            NaN            Group B
493                  Togo            NaN            NaN            Group B

                                  SpecialWinConditions  \
13                                                 NaN
46                                                 NaN
72                                                 NaN
21                                                 NaN
400                                                NaN
..                                                 ...
621                                                NaN
1    Ethiopia  wins due to disqualification of othe...
489  Ghana  wins due to disqualification of other team
490  Burkina Faso  wins due to disqualification of ...
493  Ivory Coast  wins due to disqualification of o...

                         Stadium       City  Attendance
13         Kumasi Sports Stadium     Kumasi         NaN
46             Municipal Stadium   Khartoum      9770.0
72              Stade Omnisports    Yaoundé         NaN
21         Stade Bou Ali Lahouar     Sousse         NaN
400         Stade Taïeb El Mhiri       Sfax     15000.0
..                           ...        ...         ...
621  Cairo International Stadium      Cairo     75000.0
1                            NaN        NaN         NaN
489                          NaN        NaN         NaN
490                          NaN        NaN         NaN
493                          NaN        NaN         NaN

[622 rows x 12 columns]

10.	Write a Pandas program to get list from DataFrame column headers.

In [18]:
# shows the header lists
column_headers = DF.columns.tolist()
print(column_headers)

['Year', 'Date ', 'Time ', 'HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals', 'Stage', 'SpecialWinConditions', 'Stadium', 'City', 'Attendance']

11.	Write a Pandas program to append a column of your choice to your DataFrame.

In [19]:

# Creating a column with first 5 countries and filling rest of cells with null values

NewTeam = ['Rwanda', 'Malawi', 'Zambia', 'DR Congo', 'Comoros']

# Create a new Series with the new column values and NaN for the remaining cells
new_series = pd.Series(NewTeam + [np.nan] * (len(DF) - len(NewTeam)))

# Append the NewTeam column to the DataFrame
DF['NewTeam'] = new_series

# Print the modified DataFrame 
print(DF)

     Year                      Date   Time      HomeTeam       AwayTeam  \
0    1957                  10-Feb-57    NaN       Sudan           Egypt
1    1957                  10-Feb-57    NaN    Ethiopia    South Africa
2    1957                  16-Feb-57    NaN       Egypt        Ethiopia
3    1959                  22-May-59    NaN        Egypt       Ethiopia
4    1959                  25-May-59    NaN       Sudan        Ethiopia
..    ...                        ...    ...          ...            ...
617  2019  11 July 2019 (2019-07-11)  21:00  Madagascar         Tunisia
618  2019  14 July 2019 (2019-07-14)  18:00     Senegal         Tunisia
619  2019  14 July 2019 (2019-07-14)  21:00     Algeria         Nigeria
620  2019  17 July 2019 (2019-07-17)  21:00     Tunisia         Nigeria
621  2019  19 July 2019 (2019-07-19)  21:00     Senegal         Algeria

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
617            0.0            3.0        Quarter-finals
618            1.0            0.0           Semi-finals
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
617                                                NaN
618                              win after extra time
619                                                NaN
620                                                NaN
621                                                NaN

                         Stadium       City  Attendance   NewTeam
0              Municipal Stadium   Khartoum     30000.0    Rwanda
1                            NaN        NaN         NaN    Malawi
2              Municipal Stadium   Khartoum     30000.0    Zambia
3          Prince Farouk Stadium      Cairo     30000.0  DR Congo
4          Prince Farouk Stadium      Cairo     20000.0   Comoros
..                           ...        ...         ...       ...
617             Al Salam Stadium      Cairo      7568.0       NaN
618              30 June Stadium      Cairo      9143.0       NaN
619  Cairo International Stadium      Cairo     49775.0       NaN
620             Al Salam Stadium      Cairo      6340.0       NaN
621  Cairo International Stadium      Cairo     75000.0       NaN

[622 rows x 13 columns]

12.	Write a Pandas program to add 2 rows to your DataFrame.

In [20]:
# to add 2 rows
new_rows = [{'HomeTeam': 'Team A', 'AwayTeam': 'Team B', 'HomeTeamGoals': 2, 'AwayTeamGoals': 1, 'Attendance': 15000, 'Stadium': 'Stadium X'},
            {'HomeTeam': 'Team C', 'AwayTeam': 'Team D', 'HomeTeamGoals': 3, 'AwayTeamGoals': 2, 'Attendance': 20000, 'Stadium': 'Stadium Y'}]

DF = DF.append(new_rows, ignore_index=True)
print(DF)

       Year                      Date   Time    HomeTeam       AwayTeam  \
0    1957.0                  10-Feb-57    NaN     Sudan           Egypt
1    1957.0                  10-Feb-57    NaN  Ethiopia    South Africa
2    1957.0                  16-Feb-57    NaN     Egypt        Ethiopia
3    1959.0                  22-May-59    NaN      Egypt       Ethiopia
4    1959.0                  25-May-59    NaN     Sudan        Ethiopia
..      ...                        ...    ...        ...            ...
619  2019.0  14 July 2019 (2019-07-14)  21:00   Algeria         Nigeria
620  2019.0  17 July 2019 (2019-07-17)  21:00   Tunisia         Nigeria
621  2019.0  19 July 2019 (2019-07-19)  21:00   Senegal         Algeria
622     NaN                        NaN    NaN     Team A         Team B
623     NaN                        NaN    NaN     Team C         Team D

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final
622            2.0            1.0                   NaN
623            3.0            2.0                   NaN

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
619                                                NaN
620                                                NaN
621                                                NaN
622                                                NaN
623                                                NaN

                         Stadium       City  Attendance   NewTeam
0              Municipal Stadium   Khartoum     30000.0    Rwanda
1                            NaN        NaN         NaN    Malawi
2              Municipal Stadium   Khartoum     30000.0    Zambia
3          Prince Farouk Stadium      Cairo     30000.0  DR Congo
4          Prince Farouk Stadium      Cairo     20000.0   Comoros
..                           ...        ...         ...       ...
619  Cairo International Stadium      Cairo     49775.0       NaN
620             Al Salam Stadium      Cairo      6340.0       NaN
621  Cairo International Stadium      Cairo     75000.0       NaN
622                    Stadium X        NaN     15000.0       NaN
623                    Stadium Y        NaN     20000.0       NaN

[624 rows x 13 columns]

/var/folders/tl/bblcp0k11px7pqccr79xwqjr0000gn/T/ipykernel_8739/896182211.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  DF = DF.append(new_rows, ignore_index=True)

13.	Write a Pandas program to change the country ‘Uganda’ to ‘China’ in the ‘AwayTeam’ column of the DataFrame.

In [21]:
# changes the uganda to china in the AwayTeam
DF.loc[DF['AwayTeam'] == 'Uganda', 'AwayTeam'] = 'China'
print(DF)

       Year                      Date   Time    HomeTeam       AwayTeam  \
0    1957.0                  10-Feb-57    NaN     Sudan           Egypt
1    1957.0                  10-Feb-57    NaN  Ethiopia    South Africa
2    1957.0                  16-Feb-57    NaN     Egypt        Ethiopia
3    1959.0                  22-May-59    NaN      Egypt       Ethiopia
4    1959.0                  25-May-59    NaN     Sudan        Ethiopia
..      ...                        ...    ...        ...            ...
619  2019.0  14 July 2019 (2019-07-14)  21:00   Algeria         Nigeria
620  2019.0  17 July 2019 (2019-07-17)  21:00   Tunisia         Nigeria
621  2019.0  19 July 2019 (2019-07-19)  21:00   Senegal         Algeria
622     NaN                        NaN    NaN     Team A         Team B
623     NaN                        NaN    NaN     Team C         Team D

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final
622            2.0            1.0                   NaN
623            3.0            2.0                   NaN

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
619                                                NaN
620                                                NaN
621                                                NaN
622                                                NaN
623                                                NaN

                         Stadium       City  Attendance   NewTeam
0              Municipal Stadium   Khartoum     30000.0    Rwanda
1                            NaN        NaN         NaN    Malawi
2              Municipal Stadium   Khartoum     30000.0    Zambia
3          Prince Farouk Stadium      Cairo     30000.0  DR Congo
4          Prince Farouk Stadium      Cairo     20000.0   Comoros
..                           ...        ...         ...       ...
619  Cairo International Stadium      Cairo     49775.0       NaN
620             Al Salam Stadium      Cairo      6340.0       NaN
621  Cairo International Stadium      Cairo     75000.0       NaN
622                    Stadium X        NaN     15000.0       NaN
623                    Stadium Y        NaN     20000.0       NaN

[624 rows x 13 columns]

14.	Write a Pandas program to reset index in your DataFrame.

In [22]:
#drops the indexes
DF.reset_index(drop=True, inplace=True)
print(DF)

       Year                      Date   Time    HomeTeam       AwayTeam  \
0    1957.0                  10-Feb-57    NaN     Sudan           Egypt
1    1957.0                  10-Feb-57    NaN  Ethiopia    South Africa
2    1957.0                  16-Feb-57    NaN     Egypt        Ethiopia
3    1959.0                  22-May-59    NaN      Egypt       Ethiopia
4    1959.0                  25-May-59    NaN     Sudan        Ethiopia
..      ...                        ...    ...        ...            ...
619  2019.0  14 July 2019 (2019-07-14)  21:00   Algeria         Nigeria
620  2019.0  17 July 2019 (2019-07-17)  21:00   Tunisia         Nigeria
621  2019.0  19 July 2019 (2019-07-19)  21:00   Senegal         Algeria
622     NaN                        NaN    NaN     Team A         Team B
623     NaN                        NaN    NaN     Team C         Team D

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final
622            2.0            1.0                   NaN
623            3.0            2.0                   NaN

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
619                                                NaN
620                                                NaN
621                                                NaN
622                                                NaN
623                                                NaN

                         Stadium       City  Attendance   NewTeam
0              Municipal Stadium   Khartoum     30000.0    Rwanda
1                            NaN        NaN         NaN    Malawi
2              Municipal Stadium   Khartoum     30000.0    Zambia
3          Prince Farouk Stadium      Cairo     30000.0  DR Congo
4          Prince Farouk Stadium      Cairo     20000.0   Comoros
..                           ...        ...         ...       ...
619  Cairo International Stadium      Cairo     49775.0       NaN
620             Al Salam Stadium      Cairo      6340.0       NaN
621  Cairo International Stadium      Cairo     75000.0       NaN
622                    Stadium X        NaN     15000.0       NaN
623                    Stadium Y        NaN     20000.0       NaN

[624 rows x 13 columns]

15.	Write a Pandas program to check whether the ‘Stadium’ column is present in your DataFrame or not.

In [23]:
# tests the existence of Stadium in the dataset
if 'Stadium' in DF.columns:
    print("The 'Stadium' column is present in the DataFrame.")
else:
    print("The 'Stadium' column is not present in the DataFrame.")

The 'Stadium' column is present in the DataFrame.

16.	Write a Pandas program to convert the datatype of the ‘AwayTeamGoals’. (int to float)

In [24]:
# convert the AwayTeamGoals from int to float 
DF['AwayTeamGoals'] = DF['AwayTeamGoals'].astype(float)
print(DF.dtypes)

Year                    float64
Date                     object
Time                     object
HomeTeam                 object
AwayTeam                 object
HomeTeamGoals           float64
AwayTeamGoals           float64
Stage                    object
SpecialWinConditions     object
Stadium                  object
City                     object
Attendance              float64
NewTeam                  object
dtype: object

17.	Write a Pandas program to remove the last 10 rows from your DataFrame.

In [25]:
# removes the last 10 rows
DF = DF[:-10]
print(DF)

       Year                     Date   Time      HomeTeam       AwayTeam  \
0    1957.0                 10-Feb-57    NaN       Sudan           Egypt
1    1957.0                 10-Feb-57    NaN    Ethiopia    South Africa
2    1957.0                 16-Feb-57    NaN       Egypt        Ethiopia
3    1959.0                 22-May-59    NaN        Egypt       Ethiopia
4    1959.0                 25-May-59    NaN       Sudan        Ethiopia
..      ...                       ...    ...          ...            ...
609  2019.0  6 July 2019 (2019-07-06)  21:00       Egypt    South Africa
610  2019.0  7 July 2019 (2019-07-07)  18:00  Madagascar        DR Congo
611  2019.0  7 July 2019 (2019-07-07)  21:00     Algeria          Guinea
612  2019.0  8 July 2019 (2019-07-08)  18:00        Mali     Ivory Coast
613  2019.0  8 July 2019 (2019-07-08)  21:00       Ghana         Tunisia

     HomeTeamGoals  AwayTeamGoals             Stage  \
0              1.0            2.0        Semifinals
1              NaN            NaN        Semifinals
2              4.0           10.0             Final
3              4.0            0.0  Final Tournament
4              1.0            0.0  Final Tournament
..             ...            ...               ...
609            0.0            1.0       Round of 16
610            2.0            2.0       Round of 16
611            3.0            0.0       Round of 16
612            0.0            1.0       Round of 16
613            1.0            1.0       Round of 16

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
609                                                NaN
610                  Madagascar  win on Penalities 4-2
611                                                NaN
612                                                NaN
613                      Tunisia win on Penalities 4-5

                         Stadium         City  Attendance   NewTeam
0              Municipal Stadium     Khartoum     30000.0    Rwanda
1                            NaN          NaN         NaN    Malawi
2              Municipal Stadium     Khartoum     30000.0    Zambia
3          Prince Farouk Stadium        Cairo     30000.0  DR Congo
4          Prince Farouk Stadium        Cairo     20000.0   Comoros
..                           ...          ...         ...       ...
609  Cairo International Stadium        Cairo     75000.0       NaN
610           Alexandria Stadium   Alexandria      5890.0       NaN
611              30 June Stadium        Cairo      8205.0       NaN
612                 Suez Stadium         Suez      7672.0       NaN
613             Ismailia Stadium     Ismailia      8890.0       NaN

[614 rows x 13 columns]

18.	Write a Pandas program to iterate over rows in your DataFrame.

In [26]:
# this iterates through the rows
for index, row in DF.iterrows():
    print(row['HomeTeam'], row['AwayTeam'], row['HomeTeamGoals'], row['AwayTeamGoals'])

Sudan   Egypt 1.0 2.0
Ethiopia   South Africa nan nan
Egypt   Ethiopia 4.0 10.0
Egypt  Ethiopia 4.0 0.0
Sudan   Ethiopia 1.0 0.0
Egypt  Sudan 2.0 1.0
Ethiopia   Tunisia 4.0 2.0
Egypt  Uganda 2.0 1.0
Tunisia   Uganda 3.0 0.0
Ethiopia  Egypt 4.0 2.0
Ghana   Tunisia 1.0 1.0
Ghana   Ethiopia 2.0 0.0
Ethiopia   Tunisia 4.0 2.0
Egypt  Nigeria 6.0 3.0
Egypt  Sudan 2.0 2.0
Sudan   Nigeria 4.0 0.0
Egypt  Ethiopia 3.0 0.0
Ghana   Sudan 3.0 0.0
Tunisia   Ethiopia 4.0 0.0
Senegal   Tunisia 0.0 0.0
Senegal   Ethiopia 5.0 1.0
Ghana   Congo-Léopoldville 5.0 2.0
Ivory Coast   Congo-Léopoldville 3.0 0.0
Ghana   Ivory Coast 4.0 1.0
Senegal   Ivory Coast 0.0 1.0
Ghana   Tunisia 3.0 2.0
Ethiopia   Uganda 2.0 1.0
Ivory Coast   Algeria 3.0 0.0
Ethiopia   Ivory Coast 1.0 0.0
Algeria   Uganda 4.0 0.0
Ivory Coast   Uganda 2.0 1.0
Ethiopia   Algeria 3.0 1.0
Ghana   Senegal 2.0 2.0
Congo-Kinshasa   Congo-Brazzaville 3.0 0.0
Senegal   Congo-Brazzaville 2.0 1.0
Ghana   Congo-Kinshasa 2.0 1.0
Congo-Kinshasa   Senegal 2.0 1.0
Ghana   Congo-Brazzaville 3.0 1.0
Ethiopia   Congo-Kinshasa 2.0 3.0
Ghana   Ivory Coast 4.0 3.0
Ivory Coast   Ethiopia 1.0 0.0
Congo-Kinshasa   Ghana 1.0 0.0
Cameroon   Ivory Coast 3.0 2.0
Sudan   Ethiopia 3.0 0.0
Cameroon   Ethiopia 3.0 2.0
Ivory Coast   Sudan 1.0 0.0
Ivory Coast   Ethiopia 6.0 1.0
Sudan   Cameroon 2.0 1.0
Ghana   Congo-Kinshasa 2.0 0.0
United Arab Rep.   Guinea 4.0 1.0
Congo-Kinshasa   Guinea 2.0 2.0
United Arab Rep.   Ghana 1.0 1.0
Guinea   Ghana 1.0 1.0
United Arab Rep.   Congo-Kinshasa 1.0 0.0
Ivory Coast   Ghana 1.0 2.0
United Arab Rep.   Sudan 1.0 2.0
United Arab Rep.   Ivory Coast 3.0 1.0
Sudan   Ghana 1.0 0.0
Cameroon   Kenya 2.0 1.0
Mali   Togo 3.0 3.0
Mali   Kenya 1.0 1.0
Cameroon   Togo 2.0 0.0
Togo   Kenya 1.0 1.0
Cameroon   Mali 1.0 1.0
Congo   Morocco 1.0 1.0
Zaire   Sudan 1.0 1.0
Morocco   Sudan 1.0 1.0
Zaire   Congo 2.0 0.0
Morocco   Zaire 1.0 1.0
Congo   Sudan 4.0 2.0
Cameroon   Congo 0.0 1.0
Zaire   Mali 3.0 4.0
Cameroon   Zaire 5.0 2.0
Congo   Mali 3.0 2.0
Egypt   Uganda 2.0 1.0
Zambia   Ivory Coast 1.0 0.0
Egypt   Zambia 3.0 1.0
Ivory Coast   Uganda 2.0 2.0
Egypt   Ivory Coast 2.0 0.0
Zambia   Uganda 1.0 0.0
Zaire   Guinea 2.0 1.0
Congo   Mauritius 2.0 0.0
Guinea   Mauritius 2.0 1.0
Congo   Zaire 2.0 1.0
Congo   Guinea 1.0 1.0
Zaire   Mauritius 4.0 1.0
Egypt   Zaire 2.0 3.0
Congo   Zambia 2.0 4.0
Congo   Egypt 0.0 4.0
Zaire   Zambia 2.0 2.0
Zaire   Zambia 2.0 0.0
Ethiopia   Uganda 2.0 0.0
Egypt   Guinea 1.0 1.0
Egypt   Uganda 2.0 1.0
Ethiopia   Guinea 1.0 2.0
Guinea   Uganda 2.0 1.0
Ethiopia   Egypt 1.0 1.0
Nigeria   Zaire 4.0 2.0
Morocco   Sudan 2.0 2.0
Nigeria   Sudan 1.0 0.0
Morocco   Zaire 1.0 0.0
Morocco   Nigeria 3.0 1.0
Zaire   Sudan 1.0 1.0
Guinea   Nigeria 1.0 1.0
Morocco   Egypt 2.0 1.0
Morocco   Nigeria 2.0 1.0
Guinea   Egypt 4.0 2.0
Nigeria   Egypt 3.0 2.0
Guinea   Morocco 1.0 1.0
Ghana   Zambia 2.0 1.0
Nigeria   Upper Volta 4.0 2.0
Zambia   Upper Volta 2.0 0.0
Nigeria   Ghana 1.0 1.0
Zambia   Nigeria 0.0 0.0
Ghana   Upper Volta 3.0 0.0
Morocco   Tunisia 1.0 1.0
Uganda   Congo 3.0 1.0
Tunisia   Uganda 3.0 1.0
Morocco   Congo 1.0 0.0
Congo   Tunisia 0.0 0.0
Uganda   Morocco 3.0 0.0
Ghana   Tunisia 1.0 0.0
Uganda   Nigeria 2.0 1.0
Nigeria   Tunisia 1.0 11.0
Ghana   Uganda 2.0 0.0
Nigeria   Tanzania 3.0 1.0
Egypt   Ivory Coast 2.0 1.0
Egypt   Tanzania 2.0 1.0
Nigeria   Ivory Coast 0.0 0.0
Ivory Coast   Tanzania 1.0 1.0
Nigeria   Egypt 1.0 0.0
Ghana   Algeria 0.0 0.0
Morocco   Guinea 1.0 1.0
Algeria   Morocco 1.0 0.0
Ghana   Guinea 1.0 0.0
Algeria   Guinea 3.0 2.0
Morocco   Ghana 1.0 0.0
Nigeria   Morocco 1.0 0.0
Algeria   Egypt 2.0 2.0
Morocco   Egypt 2.0 0.0
Nigeria   Algeria 3.0 0.0
Libya   Ghana 2.0 2.0
Cameroon   Tunisia 1.0 1.0
Cameroon   Ghana 0.0 0.0
Libya   Tunisia 2.0 0.0
Ghana   Tunisia 1.0 0.0
Libya   Cameroon 0.0 0.0
Nigeria   Ethiopia 3.0 0.0
Algeria   Zambia 1.0 0.0
Zambia   Ethiopia 1.0 0.0
Algeria   Nigeria 2.0 1.0
Algeria   Ethiopia 0.0 0.0
Zambia   Nigeria 3.0 0.0
Ghana   Algeria 3.0 2.0
Libya   Zambia 2.0 1.0
Zambia   Algeria 2.0 0.0
Ghana   Libya 1.0 1.0
Ivory Coast   Togo 3.0 0.0
Egypt   Cameroon 1.0 0.0
Cameroon   Togo 4.0 1.0
Ivory Coast   Egypt 1.0 2.0
Egypt   Togo 0.0 0.0
Ivory Coast   Cameroon 0.0 2.0
Ghana   Nigeria 1.0 2.0
Algeria   Malawi 3.0 0.0
Malawi   Nigeria 2.0 2.0
Algeria   Ghana 2.0 0.0
Algeria   Nigeria 0.0 0.0
Ghana   Malawi 1.0 0.0
Egypt   Nigeria 2.0 2.0
Algeria   Cameroon 0.0 0.0
Algeria   Egypt 3.0 1.0
Cameroon   Nigeria 3.0 1.0
Senegal   Egypt 1.0 0.0
Ivory Coast   Mozambique 3.0 0.0
Senegal   Mozambique 2.0 0.0
Egypt   Ivory Coast 2.0 0.0
Ivory Coast   Senegal 1.0 0.0
Egypt   Mozambique 2.0 0.0
Algeria   Morocco 0.0 0.0
Cameroon   Zambia 3.0 2.0
Algeria   Zambia 0.0 0.0
Cameroon   Morocco 1.0 1.0
Morocco   Zambia 1.0 0.0
Cameroon   Algeria 3.0 2.0
Cameroon   Ivory Coast 1.0 0.0
Egypt   Morocco 1.0 0.0
Ivory Coast   Morocco 3.0 2.0
Egypt   Cameroon 0.0 0.0
Morocco   Zaire 1.0 1.0
Ivory Coast   Algeria 1.0 1.0
Ivory Coast   Zaire 1.0 1.0
Morocco   Algeria 1.0 0.0
Algeria   Zaire 1.0 0.0
Morocco   Ivory Coast 0.0 0.0
Cameroon   Egypt 1.0 0.0
Nigeria   Kenya 3.0 0.0
Cameroon   Nigeria 1.0 1.0
Egypt   Kenya 3.0 0.0
Cameroon   Kenya 0.0 0.0
Nigeria   Egypt 0.0 0.0
Nigeria   Algeria 1.0 1.0
Morocco   Cameroon 0.0 1.0
Morocco   Algeria 1.0 1.0
Cameroon   Nigeria 1.0 0.0
Algeria   Nigeria 5.0 1.0
Ivory Coast   Egypt 3.0 1.0
Nigeria   Egypt 1.0 0.0
Algeria   Ivory Coast 3.0 0.0
Nigeria   Ivory Coast 1.0 0.0
Algeria   Egypt 2.0 0.0
Zambia   Cameroon 1.0 0.0
Senegal   Kenya 0.0 0.0
Zambia   Kenya 1.0 0.0
Senegal   Cameroon 2.0 0.0
Zambia   Senegal 0.0 0.0
Cameroon   Kenya 2.0 0.0
Zambia   Nigeria 0.0 2.0
Algeria   Senegal 2.0 1.0
Zambia   Senegal 1.0 0.0
Algeria   Nigeria 1.0 0.0
Nigeria   Senegal 2.0 1.0
Nigeria   Kenya 2.0 1.0
Senegal   Kenya 3.0 0.0
Cameroon   Morocco 1.0 0.0
Morocco   Zaire 1.0 1.0
Cameroon   Zaire 1.0 1.0
Ivory Coast   Algeria 3.0 0.0
Ivory Coast   Congo 0.0 0.0
Algeria   Congo 1.0 1.0
Zambia   Egypt 1.0 0.0
Ghana   Zambia 1.0 0.0
Ghana   Egypt 1.0 0.0
Nigeria   Zaire 1.0 0.0
Cameroon   Senegal 1.0 0.0
Ivory Coast   Zambia 1.0 0.0
Ghana   Congo 2.0 1.0
Ghana   Nigeria 2.0 1.0
Cameroon   Ivory Coast 0.0 0.0
Nigeria   Cameroon 2.0 1.0
Ivory Coast   Ghana 0.0 0.0
Tunisia   Mali 0.0 2.0
Mali   Zaire 0.0 1.0
Tunisia   Zaire 1.0 1.0
Nigeria   Gabon 3.0 0.0
Egypt   Gabon 4.0 0.0
Nigeria   Egypt 0.0 0.0
Ivory Coast   Sierra Leone 4.0 0.0
Zambia   Sierra Leone 0.0 0.0
Zambia   Ivory Coast 1.0 0.0
Ghana   Guinea 1.0 0.0
Senegal   Guinea 2.0 1.0
Ghana   Senegal 1.0 0.0
Zaire   Nigeria 0.0 2.0
Egypt   Mali 0.0 1.0
Zambia   Senegal 1.0 0.0
Ghana   Ivory Coast 1.0 2.0
Nigeria   Ivory Coast 2.0 2.0
Zambia   Mali 4.0 0.0
Ivory Coast   Mali 3.0 1.0
Nigeria   Zambia 2.0 1.0
South Africa   Cameroon 3.0 0.0
Egypt   Angola 2.0 1.0
Cameroon   Egypt 2.0 1.0
South Africa   Angola 1.0 0.0
South Africa   Egypt 0.0 1.0
Angola   Cameroon 3.0 3.0
Zambia   Algeria 0.0 0.0
Sierra Leone   Burkina Faso 2.0 1.0
Algeria   Sierra Leone 2.0 0.0
Zambia   Burkina Faso 5.0 1.0
Algeria   Burkina Faso 2.0 1.0
Zambia   Sierra Leone 4.0 0.0
Gabon   Liberia 1.0 2.0
Gabon   Zaire 2.0 0.0
Zaire   Liberia 2.0 0.0
Ghana   Ivory Coast 2.0 0.0
Tunisia   Mozambique 1.0 1.0
Ghana   Tunisia 2.0 1.0
Ivory Coast   Mozambique 1.0 0.0
Tunisia   Ivory Coast 3.0 1.0
Ghana   Mozambique 2.0 0.0
South Africa   Algeria 2.0 1.0
Zambia   Egypt 3.0 1.0
Gabon   Tunisia 1.0 1.0
Ghana   Zaire 1.0 0.0
South Africa   Ghana 3.0 0.0
Zambia   Tunisia 2.0 4.0
Ghana   Zambia 0.0 1.0
South Africa   Tunisia 2.0 0.0
Burkina Faso   Cameroon 0.0 1.0
Algeria   Guinea 0.0 1.0
Cameroon   Guinea 2.0 2.0
Burkina Faso   Algeria 2.0 1.0
Burkina Faso   Guinea 1.0 0.0
Cameroon   Algeria 2.0 1.0
DR Congo   Togo 2.0 1.0
Ghana   Tunisia 2.0 0.0
Tunisia   DR Congo 2.0 1.0
Togo   Ghana 2.0 1.0
DR Congo   Ghana 1.0 0.0
Tunisia   Togo 3.0 1.0
South Africa   Angola 0.0 0.0
Ivory Coast   Namibia 4.0 3.0
Ivory Coast   South Africa 1.0 1.0
Angola   Namibia 3.0 3.0
Ivory Coast   Angola 5.0 2.0
South Africa   Namibia 4.0 1.0
Morocco   Zambia 1.0 1.0
Egypt   Mozambique 2.0 0.0
Egypt   Zambia 4.0 0.0
Morocco   Mozambique 3.0 0.0
Zambia   Mozambique 3.0 1.0
Morocco   Egypt 1.0 0.0
Cameroon   DR Congo 0.0 1.0
Tunisia   Burkina Faso 1.0 1.0
Ivory Coast   Egypt 0.0 0.0
Morocco   South Africa 1.0 2.0
DR Congo   South Africa 1.0 2.0
Burkina Faso   Egypt 0.0 2.0
DR Congo   Burkina Faso 4.0 4.0
South Africa   Egypt 0.0 2.0
Ghana   Cameroon 1.0 1.0
Ivory Coast   Togo 1.0 1.0
Ghana   Togo 2.0 0.0
Cameroon   Ivory Coast 3.0 0.0
Ghana   Ivory Coast 0.0 2.0
Cameroon   Togo 0.0 1.0
South Africa   Gabon 3.0 1.0
DR Congo   Algeria 0.0 0.0
South Africa   DR Congo 1.0 0.0
Algeria   Gabon 3.0 1.0
South Africa   Algeria 1.0 1.0
DR Congo   Gabon 0.0 0.0
Egypt   Zambia 2.0 0.0
Burkina Faso   Senegal 1.0 3.0
Egypt   Senegal 1.0 0.0
Zambia   Burkina Faso 1.0 1.0
Egypt   Burkina Faso 4.0 2.0
Zambia   Senegal 2.0 2.0
Nigeria   Tunisia 4.0 2.0
Morocco   Congo 1.0 0.0
Nigeria   Congo 0.0 0.0
Tunisia   Morocco 0.0 0.0
Nigeria   Morocco 2.0 0.0
Tunisia   Congo 1.0 0.0
Cameroon   Algeria 2.0 1.0
South Africa   Ghana 1.0 0.0
Egypt   Tunisia 0.0 1.0
Nigeria   Senegal 2.0 1.0
Nigeria   South Africa 2.0 0.0
Cameroon   Tunisia 3.0 0.0
South Africa   Tunisia 2.0 2.0
Nigeria   Cameroon 2.0 2.0
Mali   Liberia 1.0 1.0
Algeria   Nigeria 0.0 1.0
Mali   Nigeria 0.0 0.0
Liberia   Algeria 2.0 2.0
Mali   Algeria 2.0 0.0
Liberia   Nigeria 0.0 1.0
South Africa   Burkina Faso 0.0 0.0
Morocco   Ghana 0.0 0.0
South Africa   Ghana 0.0 0.0
Burkina Faso   Morocco 1.0 2.0
South Africa   Morocco 3.0 1.0
Burkina Faso   Ghana 1.0 2.0
Cameroon   DR Congo 1.0 0.0
Togo   Ivory Coast 0.0 0.0
Cameroon   Ivory Coast 1.0 0.0
DR Congo   Togo 0.0 0.0
Cameroon   Togo 3.0 0.0
DR Congo   Ivory Coast 3.0 1.0
Egypt   Senegal 0.0 1.0
Zambia   Tunisia 0.0 0.0
Egypt   Tunisia 1.0 0.0
Senegal   Zambia 1.0 0.0
Egypt   Zambia 2.0 1.0
Senegal   Tunisia 0.0 0.0
South Africa   Mali 0.0 2.0
Nigeria   Ghana 1.0 0.0
Cameroon   Egypt 1.0 0.0
Senegal   DR Congo 2.0 0.0
Nigeria   Senegal 1.0 2.0
Mali   Cameroon 0.0 3.0
Nigeria   Mali 1.0 0.0
Senegal   Cameroon 0.0 0.0
Tunisia   Rwanda 2.0 1.0
DR Congo   Guinea 1.0 2.0
Rwanda   Guinea 1.0 1.0
Tunisia   DR Congo 3.0 0.0
Tunisia   Guinea 1.0 1.0
Rwanda   DR Congo 1.0 0.0
Kenya   Mali 1.0 3.0
Senegal   Burkina Faso 0.0 0.0
Senegal   Kenya 3.0 0.0
Burkina Faso   Mali 1.0 3.0
Senegal   Mali 1.0 1.0
Burkina Faso   Kenya 0.0 3.0
Zimbabwe   Egypt 1.0 2.0
Cameroon   Algeria 1.0 1.0
Cameroon   Zimbabwe 5.0 3.0
Algeria   Egypt 2.0 1.0
Cameroon   Egypt 0.0 0.0
Algeria   Zimbabwe 1.0 2.0
Nigeria   Morocco 0.0 1.0
South Africa   Benin 2.0 0.0
Nigeria   South Africa 4.0 0.0
Morocco   Benin 4.0 0.0
Morocco   South Africa 1.0 1.0
Nigeria   Benin 2.0 1.0
Mali   Guinea 2.0 1.0
Tunisia   Senegal 1.0 0.0
Cameroon   Nigeria 1.0 2.0
Morocco   Algeria 3.0 1.0
Tunisia   Nigeria 1.0 1.0
Morocco   Mali 4.0 0.0
Nigeria   Mali 2.0 1.0
Tunisia   Morocco 2.0 1.0
Egypt   Libya 3.0 0.0
Morocco   Ivory Coast 0.0 1.0
Libya   Ivory Coast 1.0 2.0
Egypt   Morocco 0.0 0.0
Egypt   Ivory Coast 3.0 1.0
Libya   Morocco 0.0 0.0
Cameroon   Angola 3.0 1.0
Togo   DR Congo 0.0 2.0
Angola   DR Congo 0.0 0.0
Cameroon   Togo 2.0 0.0
Angola   Togo 3.0 2.0
Cameroon   DR Congo 2.0 0.0
Tunisia   Zambia 4.0 1.0
South Africa   Guinea 0.0 2.0
Zambia   Guinea 1.0 2.0
Tunisia   South Africa 2.0 0.0
Tunisia   Guinea 0.0 3.0
Zambia   South Africa 1.0 0.0
Nigeria   Ghana 1.0 0.0
Zimbabwe   Senegal 0.0 2.0
Ghana   Senegal 1.0 0.0
Nigeria   Zimbabwe 2.0 0.0
Nigeria   Senegal 2.0 1.0
Ghana   Zimbabwe 1.0 2.0
Guinea   Senegal 2.0 3.0
Egypt   DR Congo 4.0 1.0
Nigeria   Tunisia 1.0 1.0
Cameroon   Ivory Coast 1.0 1.0
Egypt   Senegal 2.0 1.0
Nigeria   Ivory Coast 0.0 1.0
Senegal   Nigeria 0.0 1.0
Egypt   Ivory Coast 0.0 0.0
Ghana   Guinea 2.0 1.0
Namibia   Morocco 1.0 5.0
Guinea   Morocco 3.0 2.0
Ghana   Namibia 1.0 0.0
Ghana   Morocco 2.0 0.0
Guinea   Namibia 1.0 1.0
Nigeria   Ivory Coast 0.0 1.0
Mali   Benin 1.0 0.0
Ivory Coast   Benin 4.0 1.0
Nigeria   Mali 0.0 0.0
Nigeria   Benin 2.0 0.0
Ivory Coast   Mali 3.0 0.0
Egypt   Cameroon 4.0 2.0
Sudan   Zambia 0.0 3.0
Cameroon   Zambia 5.0 1.0
Egypt   Sudan 3.0 0.0
Cameroon   Sudan 3.0 0.0
Egypt   Zambia 1.0 1.0
Tunisia   Senegal 2.0 2.0
South Africa   Angola 1.0 1.0
Senegal   Angola 1.0 3.0
Tunisia   South Africa 3.0 1.0
Senegal   South Africa 1.0 1.0
Tunisia   Angola 0.0 0.0
Ghana   Nigeria 2.0 1.0
Ivory Coast   Guinea 5.0 0.0
Egypt   Angola 2.0 1.0
Tunisia   Cameroon 2.0 3.0
Ghana   Cameroon 0.0 1.0
Ivory Coast   Egypt 1.0 4.0
Ghana   Ivory Coast 4.0 2.0
Cameroon   Egypt 0.0 1.0
Angola   Mali 4.0 4.0
Malawi   Algeria 3.0 0.0
Mali   Algeria 0.0 1.0
Angola   Malawi 2.0 0.0
Angola   Algeria 0.0 0.0
Mali   Malawi 3.0 1.0
Ivory Coast   Burkina Faso 0.0 0.0
Ghana   Togo nan nan
Burkina Faso   Togo nan nan
Ivory Coast   Ghana 3.0 1.0
Burkina Faso   Ghana 0.0 1.0
Ivory Coast   Togo nan nan
Egypt   Nigeria 3.0 1.0
Mozambique   Benin 2.0 2.0
Nigeria   Benin 1.0 0.0
Egypt   Mozambique 2.0 0.0
Egypt   Benin 2.0 0.0
Nigeria   Mozambique 3.0 0.0
Cameroon   Gabon 0.0 1.0
Zambia   Tunisia 1.0 1.0
Gabon   Tunisia 0.0 0.0
Cameroon   Zambia 3.0 2.0
Gabon   Zambia 1.0 2.0
Cameroon   Tunisia 2.0 2.0
Angola   Ghana 0.0 1.0
Ivory Coast   Algeria 2.0 3.0
Egypt   Cameroon 3.0 1.0
Zambia   Nigeria 0.0 0.0
Ghana   Nigeria 1.0 0.0
Algeria   Egypt 0.0 4.0
Nigeria   Algeria 1.0 0.0
Ghana   Egypt 0.0 1.0
Zambia   Sudan 3.0 0.0
Ivory Coast   Equatorial Guinea 3.0 0.0
Gabon   Mali 1.0 1.0
Ghana   Tunisia 2.0 1.0
Zambia   Ghana 1.0 0.0
Mali   Ivory Coast 0.0 1.0
Ghana   Mali 0.0 2.0
Zambia   Ivory Coast 0.0 0.0
Ghana   Cape Verde 2.0 0.0
South Africa   Mali 1.0 1.0
Ivory Coast   Nigeria 1.0 2.0
Burkina Faso   Togo 1.0 0.0
Mali   Nigeria 1.0 4.0
Burkina Faso   Ghana 1.0 1.0
Mali   Ghana 3.0 1.0
Nigeria   Burkina Faso 1.0 0.0
Congo   DR Congo 2.0 4.0
Tunisia   Equatorial Guinea 1.0 2.0
Ghana   Guinea 3.0 0.0
Ivory Coast   Algeria 3.0 1.0
DR Congo   Ivory Coast 1.0 3.0
Ghana   Equatorial Guinea 3.0 0.0
DR Congo   Equatorial Guinea 0.0 0.0
Ivory Coast   Ghana 0.0 0.0
Gabon   Guinea-Bissau 1.0 1.0
Burkina Faso   Cameroon 1.0 1.0
Gabon   Burkina Faso 1.0 1.0
Cameroon   Guinea-Bissau 2.0 1.0
Cameroon   Gabon 0.0 0.0
Guinea-Bissau   Burkina Faso 0.0 2.0
Algeria   Zimbabwe 2.0 2.0
Tunisia   Senegal 0.0 2.0
Algeria   Tunisia 1.0 2.0
Senegal   Zimbabwe 2.0 0.0
Senegal   Algeria 2.0 2.0
Zimbabwe   Tunisia 2.0 4.0
Ivory Coast   Togo 0.0 0.0
DR Congo   Morocco 1.0 0.0
Ivory Coast   DR Congo 2.0 2.0
Morocco   Togo 3.0 1.0
Morocco   Ivory Coast 1.0 0.0
Togo   DR Congo 1.0 3.0
Ghana   Uganda 1.0 0.0
Mali   Egypt 0.0 0.0
Ghana   Mali 1.0 0.0
Egypt   Uganda 1.0 0.0
Egypt   Ghana 1.0 0.0
Uganda   Mali 1.0 1.0
Burkina Faso   Tunisia 2.0 0.0
Senegal   Cameroon 0.0 0.0
DR Congo   Ghana 1.0 2.0
Egypt   Morocco 1.0 0.0
Burkina Faso   Egypt 1.0 1.0
Cameroon   Ghana 2.0 0.0
Burkina Faso   Ghana 1.0 0.0
Egypt   Cameroon 1.0 2.0
Egypt   Zimbabwe 1.0 0.0
DR Congo   Uganda 0.0 2.0
Uganda   Zimbabwe 1.0 1.0
Egypt   DR Congo 2.0 0.0
Uganda   Egypt 0.0 2.0
Zimbabwe   DR Congo 0.0 4.0
Nigeria   Burundi 1.0 0.0
Guinea   Madagascar 2.0 2.0
Nigeria   Guinea 1.0 0.0
Madagascar   Burundi 1.0 0.0
Madagascar   Nigeria 2.0 0.0
Burundi   Guinea 0.0 2.0
Senegal   Tanzania 2.0 0.0
Algeria   Kenya 2.0 0.0
Senegal   Algeria 0.0 1.0
Kenya   Tanzania 3.0 2.0
Kenya   Senegal 0.0 3.0
Tanzania   Algeria 0.0 3.0
Morocco   Namibia 1.0 0.0
Ivory Coast   South Africa 1.0 0.0
Morocco   Ivory Coast 1.0 0.0
South Africa   Namibia 1.0 0.0
South Africa   Morocco 0.0 1.0
Namibia   Ivory Coast 1.0 4.0
Tunisia   Angola 1.0 1.0
Mali   Mauritania 4.0 1.0
Tunisia   Mali 1.0 1.0
Mauritania   Angola 0.0 0.0
Mauritania   Tunisia 0.0 0.0
Angola   Mali 0.0 1.0
Cameroon   Guinea-Bissau 2.0 0.0
Ghana   Benin 2.0 2.0
Cameroon   Ghana 0.0 0.0
Benin   Guinea-Bissau 0.0 0.0
Benin   Cameroon 0.0 0.0
Guinea-Bissau   Ghana 0.0 2.0
Morocco   Benin 1.0 1.0
Uganda   Senegal 0.0 1.0
Nigeria   Cameroon 3.0 2.0
Egypt   South Africa 0.0 1.0
Madagascar   DR Congo 2.0 2.0
Algeria   Guinea 3.0 0.0
Mali   Ivory Coast 0.0 1.0
Ghana   Tunisia 1.0 1.0

19.	Write a Pandas program to change the order of your DataFrame columns.

In [27]:
# this changes the order of the columns in the dataset
DF = DF[['Stadium','AwayTeam', 'HomeTeam', 'AwayTeamGoals', 'HomeTeamGoals', 'Attendance']]
print(DF)

                         Stadium       AwayTeam     HomeTeam  AwayTeamGoals  \
0              Municipal Stadium          Egypt       Sudan             2.0
1                            NaN   South Africa    Ethiopia             NaN
2              Municipal Stadium       Ethiopia       Egypt            10.0
3          Prince Farouk Stadium       Ethiopia        Egypt            0.0
4          Prince Farouk Stadium       Ethiopia       Sudan             0.0
..                           ...            ...          ...            ...
609  Cairo International Stadium   South Africa       Egypt             1.0
610           Alexandria Stadium       DR Congo  Madagascar             2.0
611              30 June Stadium         Guinea     Algeria             0.0
612                 Suez Stadium    Ivory Coast        Mali             1.0
613             Ismailia Stadium        Tunisia       Ghana             1.0

     HomeTeamGoals  Attendance
0              1.0     30000.0
1              NaN         NaN
2              4.0     30000.0
3              4.0     30000.0
4              1.0     20000.0
..             ...         ...
609            0.0     75000.0
610            2.0      5890.0
611            3.0      8205.0
612            0.0      7672.0
613            1.0      8890.0

[614 rows x 6 columns]

20.	Write a Pandas program to delete DataFrame row(s) whose value is 0 in the ‘HomeTeamGoals’ columns.

In [28]:
# it will delete rows with 0 in the homeTeamGoals and display rows without 0
DF = DF[DF['HomeTeamGoals'] != 0]
print(DF)

                   Stadium       AwayTeam     HomeTeam  AwayTeamGoals  \
0        Municipal Stadium          Egypt       Sudan             2.0
1                      NaN   South Africa    Ethiopia             NaN
2        Municipal Stadium       Ethiopia       Egypt            10.0
3    Prince Farouk Stadium       Ethiopia        Egypt            0.0
4    Prince Farouk Stadium       Ethiopia       Sudan             0.0
..                     ...            ...          ...            ...
606       Al Salam Stadium          Benin     Morocco             1.0
608     Alexandria Stadium       Cameroon     Nigeria             2.0
610     Alexandria Stadium       DR Congo  Madagascar             2.0
611        30 June Stadium         Guinea     Algeria             0.0
613       Ismailia Stadium        Tunisia       Ghana             1.0

     HomeTeamGoals  Attendance
0              1.0     30000.0
1              NaN         NaN
2              4.0     30000.0
3              4.0     30000.0
4              1.0     20000.0
..             ...         ...
606            1.0      7500.0
608            3.0     10000.0
610            2.0      5890.0
611            3.0      8205.0
613            1.0      8890.0

[489 rows x 6 columns]